version: '2.1'

services:
  webapp12:
    image: webapp12
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8443:8443
      - 5005:5005